[global]
# Streamlit Cloud configuration
developmentMode = false

[server]
# Server configuration for Streamlit Cloud
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser configuration
gatherUsageStats = false

[theme]
# Optional: Custom theme
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
